enable to use cd

diff --git a/gh-cd b/gh-cd
--- a/gh-cd
+++ b/gh-cd
@@ -1,35 +1,29 @@
 #!/bin/bash
 set -e
 
-echo "Hello gh-cd!"
+function check_command() {
+  local c=$1
+  if ! type -p ${c} >/dev/null; then
+    echo "${c} not found on the system" >&2
+    exit 1
+  fi
+}
 
-# Snippets to help get started:
+function check() {
+  local required_command=(fzf ghq)
+  for c in ${required_command[@]}; do
+    check_command(${c})
+  done
+}
 
-# Determine if an executable is in the PATH
-# if ! type -p ruby >/dev/null; then
-#   echo "Ruby not found on the system" >&2
-#   exit 1
-# fi
+function run() {
+  local cc="cat"
+  if ! type -p "bat" >/dev/null; then
+    cc="bat"
+  fi
+  repo_path=`ghq list --full-path | fzf --reverse --preview "${cc} {1}/README.md"`
+  \cd ${repo_path}
+}
 
-# Pass arguments through to another command
-# gh issue list "$@" -R cli/cli
-
-# Using the gh api command to retrieve and format information
-# QUERY='
-#   query($endCursor: String) {
-#     viewer {
-#       repositories(first: 100, after: $endCursor) {
-#         nodes {
-#           nameWithOwner
-#           stargazerCount
-#         }
-#       }
-#     }
-#   }
-# '
-# TEMPLATE='
-#   {{- range $repo := .data.viewer.repositories.nodes -}}
-#     {{- printf "name: %s - stargazers: %v\n" $repo.nameWithOwner $repo.stargazerCount -}}
-#   {{- end -}}
-# '
-# exec gh api graphql -f query="${QUERY}" --paginate --template="${TEMPLATE}"
+check()
+run()
