enable to open dir with tmux new window

diff --git a/gh-ghq-cd b/gh-ghq-cd
--- a/gh-ghq-cd
+++ b/gh-ghq-cd
@@ -1,6 +1,20 @@
 #!/bin/bash
 set -e
 
+use_tmux=false
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+  --tmux)
+    use_tmux=true
+    shift
+    ;;
+  *)
+    echo "Unknown argument: $1"
+    exit 1
+    ;;
+  esac
+done
+
 function exist_command() {
   local c=$1
   if ! type -p ${c} >/dev/null; then
@@ -17,6 +31,10 @@ function check() {
       exit 1
     fi
   done
+  if ${use_tmux} && ! exist_command "tmux"; then
+    echo "tmux not found on the system" >&2
+    exit 1
+  fi
 }
 
 function choose() {
@@ -27,8 +45,15 @@ function choose() {
   ghq list --full-path | fzf --reverse --preview "${cc} {1}/README.md"
 }
 
+function tmux_new_window() {
+  local dir=$1
+  repo=$(basename "${dir}")
+  tmux new-window -n "${repo}" -c "${dir}"
+}
+
 check
 selected="$(choose)"
 [ -n "${selected}" ] || exit 1
+$use_tmux && tmux_new_window "${selected}" && exit 0
 \cd ${selected}
 $SHELL
